config/routes.rb
CrowdfundingExperiment::Application.routes.draw do

	match "/instructions" => "users#instructions", :as => :instructions
	match "/instructions_iframe" => "users#instructions_iframe", :as => :instructions_iframe
	
	match "/questions" => "users#questions", :as => :questions
	match "/questions/submit" => "users#submit"
	
	match "/preferences/:id/flag" => "preferences#flag", :as => :flag_user
	match "/preferences/submit-flag" => "preferences#flag_submit"
	match "/preferences/:id/unflag" => "preferences#unflag", :as => :unflag_user
	
	match "/contributions/submit" => "contributions#submit"
	  
  match "/rounds/:id/summary" => "rounds#summary", :as => :round_summary
  match "/rounds/:id/summary/waiting" => "rounds#waiting_for_summary", :as => :summary_waiting
  match "/rounds/:id/waiting" => "rounds#waiting_for_round", :as => :round_waiting
  
  match "/experiments/:id/admin" => "experiments#dashboard", :as => :dashboard
  match "/experiments/:id/users" => "experiments#users", :as => :experiment_users
  match "/experiments/:id/summary" => "experiments#summary", :as => :experiment_summary
  match "/experiments/:id/final-summary/waiting" => "experiments#waiting_for_summary", :as => :experiment_summary_waiting
  match "/experiments/:id/final-summary" => "experiments#final_summary", :as => :final_experiment_summary
  
  resources :users, :only => [:create]
  resources :projects, :only => [:create]
  resources :rounds, :only => [:create, :show]
  resources :experiments, :only => [:new, :create, :index]
  resources :preferences, :only => [:create]
  resource :user_sessions, :only => [:create, :destroy]
  resources :contributions, :only => [:create]

  root :to => "user_sessions#new"
end

app/models/round.rb
class Round < ActiveRecord::Base

	belongs_to :group
	has_one :experiment, :through => :group
	has_many :projects, :dependent => :destroy
	has_many :prefs, :class_name => 'Preferences'
	has_many :users, :through => :prefs
	has_many :contributions
	
	after_create :generate_projects
	
	def check_if_all_done
		self.prefs.each do |p|
			if !p.finished_and_ready
				return false
			end
		end
		
		self.round_over
	end
		
	def generate_projects
		@project = Project.new
		@project.admin_name = 'A'
		@project.start_amount = PROJECT_START_AMOUNTS[0]
		@project.save!
		self.projects << @project

		@project = Project.new
		@project.admin_name = 'B'
		@project.start_amount = PROJECT_START_AMOUNTS[1]
		@project.save!
		self.projects << @project
		
		@project = Project.new
		@project.admin_name = 'C'
		@project.start_amount = PROJECT_START_AMOUNTS[2]
		@project.save!
		self.projects << @project
		
		@project = Project.new
		@project.admin_name = 'D'
		@project.start_amount = PROJECT_START_AMOUNTS[3]
		@project.save!
		self.projects << @project
		
		self.save!
	end
	
	def round_started
		self.start_time = DateTime.now
		self.save!
	end
	
	def round_over
		self.end_time = DateTime.now
		self.save!
		
		self.projects.each do |p|
			p.funded_amount = p.start_amount
			p.contributions.each do |c|
				p.funded_amount += c.amount
			end
			p.save!
		end
		
		@experiment = self.experiment
			
		self.prefs.each do |p|
			p.round_payout = 0
			
			@total = 0

			@total = Contribution.where(:user_id => p.user_id, :project_id => self.projects[0].id).first.amount + Contribution.where(:user_id => p.user_id, :project_id => self.projects[1].id).first.amount + Contribution.where(:user_id => p.user_id, :project_id => self.projects[2].id).first.amount + Contribution.where(:user_id => p.user_id, :project_id => self.projects[3].id).first.amount
			
			if p.timer_expired
				p.round_payout = AMOUNT_USER_CAN_DONATE_PER_ROUND
			else
				p.round_payout = AMOUNT_USER_CAN_DONATE_PER_ROUND - @total
			end
			
			if self.projects[0].funded?
				p.round_payout += p.a_payout
			elsif @experiment.return_credits
				p.round_payout += Contribution.where(:user_id => p.user_id, :project_id => self.projects[0].id).first.amount
			end
			
			if self.projects[1].funded?
				p.round_payout += p.b_payout
			elsif @experiment.return_credits
				p.round_payout += Contribution.where(:user_id => p.user_id, :project_id => self.projects[1].id).first.amount
			end
			
			if self.projects[2].funded?
				p.round_payout += p.c_payout
			elsif @experiment.return_credits
				p.round_payout += Contribution.where(:user_id => p.user_id, :project_id => self.projects[2].id).first.amount
			end
			
			if self.projects[3].funded?
				p.round_payout += p.d_payout
			elsif @experiment.return_credits
				p.round_payout += Contribution.where(:user_id => p.user_id, :project_id => self.projects[3].id).first.amount
			end
			
			@user = User.find(p.user_id)
			@user.payout += p.round_payout
			
			@user.save!
			p.save!
		end
		
		self.finished = true
		self.save!	
	end
	
end

app/controllers/rounds_controller.rb
class RoundsController < InheritedResources::Base
	def summary
		@current_round = Round.find(params[:id])
		@user = current_user
		@preferences = Preferences.where(:user_id => @user.id, :round_id => @current_round.id).first
		@contributions = Contribution.where(:user_id => current_user.id, :round_id => @current_round.id)
		
		@not_donated = AMOUNT_USER_CAN_DONATE_PER_ROUND
		@contributions.each do |c|
			@not_donated = @not_donated - c.amount
		end
		
		@temp_rounds = current_experiment.rounds.where(:number => @current_round.number + 1)
		@next_round = nil
		unless @temp_rounds.first.nil?
			if @user.preferences.where(:round_id => @temp_rounds.first.id).first.nil?
				@next_round = @temp_rounds.last
			else
				@next_round = @temp_rounds.first
			end
		end
	
		@projects = Project.where(:round_id => @current_round.id)
	end
	
	def show
		@current_round =  Round.find(params[:id])
		check_round(@current_round)
		@user = current_user
		@preferences = Preferences.where(:user_id => @user.id, :round_id => @current_round.id).first unless @user.name == 'admin'
		@projects = Project.where(:round_id => @current_round.id).order('id ASC')
	end
	
	def waiting_for_summary
		@current_round = Round.find(params[:id])
		
		if !@current_round.finished && current_user.id == @current_round.users.first.id
			@current_round.check_if_all_done
		end
		
		if current_experiment.rounds.where(:number => @current_round.number).first.finished && current_experiment.rounds.where(:number => @current_round.number).last.finished # TODO this line is really bad	
		
			if last_round?(@current_round)
				current_experiment.experiment_over if current_user == current_experiment.users.first # a cheap way to make sure it only happens once
			end
			
			redirect_to round_summary_path(@current_round)
		end
	end
	
	def waiting_for_round
		@current_round = Round.find(params[:id])
		unless current_user.group_id == @current_round.group_id
			current_user.group_id = @current_round.group_id
			current_user.save!
		end
		
		@pref = Preferences.where(:user_id => current_user.id, :round_id => @current_round.id).first if @pref.nil?
		@pref.ready_save_and_check_round unless @pref.ready_to_start
		
		if current_experiment.rounds.where(:number => @current_round.number).first.started && current_experiment.rounds.where(:number => @current_round.number).last.started # TODO this line is really bad
			current_experiment.start_experiment unless current_experiment.started
			current_experiment.current_round_number = @current_round.number
			current_experiment.save!
					
			@current_round.round_started
			redirect_to round_path(@current_round)
		end
	end
end

app/helpers/rounds_helper.rb
module RoundsHelper
	def last_round?(round)
		round == round.group.rounds.last
	end
end

app/views/rounds/_round.html.erb
<% round.projects.each do |p| %>
	<ul><%= render :partial => 'projects/stats', :object => p %></ul>
<%end%>

app/views/rounds/_stats.html.erb
<div class="row">
  <div class="span2">
    <h3>Project Name</h3>
  </div>
  
  <div class="span4">
    <h3>Funding Status</h3>
  </div>
  
  <div class="span6">
    &nbsp;
  </div>
</div>
<p>&nbsp;</p>

<% round.projects.each do |p| %>
	<%= render :partial => 'projects/stats', :locals => { :project => p }%>
<% end %>

<table class="table table-striped table-bordered">
<thead><tr><td>User</td><td>Payout (for this round)</td></tr></thead>
<% round.users.each do |u| %>
 <tr>
 	<td><%= u.name %></td>
 	<td><%= u.preferences.where(:round_id => round.id).first.round_payout %></td>
 </tr>
<% end %>
</table>

app/views/rounds/show.html.erb
<script type="text/javascript">
$(document).ready(function() {
    $.Placeholder.init();
});
</script>

<p id="notice"><%= notice %></p>

<script type="text/javascript">  
var count =61
var redirect="/contributions/submit?expired=1&current_round_id=<%=@current_round.id%>"  
var stop = false
function countDown(){  
	if (stop){return}
	
	 if (count <=0){
	  document.getElementById("timer").innerHTML = "<h2 class=\"alert alert-error\">This round has ended! Redirecting...</h2>"
	  $(".submit").hide(0);  
	  window.location = redirect;  
	 }else{  
	  count--;  
	  document.getElementById("timer").innerHTML = "This round will end in "+count+" seconds."  
	  setTimeout("countDown()", 1000)  
	 }
}  

function validateform() {
			// var total = $('#contribution_0').val() + $('#contribution_1').val() + $('#contribution_2').val() + $('#contribution_3').val();
			var total = parseInt($('#contribution_0').val()) + parseInt($('#contribution_1').val()) + parseInt($('#contribution_2').val()) + parseInt($('#contribution_3').val());
			if (total > 150 || parseInt($('#contribution_0').val()) < 0 || parseInt($('#contribution_1').val()) < 0 || parseInt($('#contribution_2').val()) < 0 || parseInt($('#contribution_3').val()) < 0) {
				$("#notice").html("<h2 class=\"alert alert-error\">Your contributions cannont total more than 150 credits and must be positive.<a class=\"close\" data-dismiss=\"alert\"><h2>x</h2></a></h2>")
				return false;
			} else 
				stop = true;
			  $(".submit").hide(0);
			  $("#loading").show(0);
			  document.getElementById("timer").innerHTML = "<h2 class=\"alert alert-success\">Answers submitted. Please wait.</h2>"
			  
			  form.submit();
	}
</script>

<script type='text/javascript'>
$(document).ready(function() {
    var credits = 150
    $('#credits').text(credits)
    $('#contribution_0').keyup(function() {
        $('#credits').text(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val());
        if(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val() < 0)
        {
	        $('#credits').css("color", "red");
        }
        else
        {
	        $('#credits').css("color", "black");
        }
    });
    $('#contribution_1').keyup(function() {
        $('#credits').text(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val());
        if(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val() < 0)
        {
	        $('#credits').css("color", "red");
        }
        else
        {
	        $('#credits').css("color", "black");
        }
    });
    $('#contribution_2').keyup(function() {
        $('#credits').text(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val());
        if(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val() < 0)
        {
	        $('#credits').css("color", "red");
        }
        else
        {
	        $('#credits').css("color", "black");
        }
    });
    $('#contribution_3').keyup(function() {
        $('#credits').text(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val());
        if(credits - $('#contribution_0').val() - $('#contribution_1').val() - $('#contribution_2').val() - $('#contribution_3').val() < 0)
        {
	        $('#credits').css("color", "red");
        }
        else
        {
	        $('#credits').css("color", "black");
        }
    });
    
}); 
</script>

<%= render @preferences if @preferences %>
<p>&nbsp;</p>
<%= form_tag "/contributions/submit" , :id => 'form' do %>

<div class="row">
  <div class="span2">
    <h3>Project Name</h3>
  </div>
  
  <div class="span4">
    <h3>Funding Status</h3>
  </div>
  
  <div class="span1">
    &nbsp;
  </div>
  
  <div class="span5">
    <h3>Contributions</h3>
  </div>
</div>

<div class="row">
  <p><% @current_round.projects.each_with_index do |p,counter| %>
  
  <div class="span2">
    <%= p.name %>
  </div>
  
  <div class="span4">
    <div class="progress">
      <div class="bar" style="width: <%= (p.start_amount.to_f / p.goal_amount) * 100 %>%;"></div>
    </div>
  </div>
  
  <div class="span1">
    <%= p.start_amount %> / <%= p.goal_amount %>
  </div>
  
  <div class="span5">
    <%#= number_field_tag "amount_#{counter}", nil, :placeholder => '0', :in => 1...150, :id => "contribution_#{counter}" %>
    <%= text_field_tag "amount_#{counter}", nil, :placeholder => '0', :in => 1...150, :id => "contribution_#{counter}" %><br>
    <%= hidden_field_tag "project_id_#{counter}", p.id %>
  </div>
  
<%end%>

<div class="row">
  <div class="span3 offset8">
    <h2>&nbsp; &nbsp;Credits: <span id="credits"></span>​</h2>
  </div>
</div>
<p>&nbsp;</p>
<div class="row submit">
  <div class="span2">
    <%= hidden_field_tag "current_round_id", @current_round.id %>
    &nbsp; &nbsp; &nbsp;<%= button_to_function "Submit", "validateform()", :class => 'btn-success btn-large' %>
  </div>  
</div> 
	<div id="loading">
		<h3><%= image_tag 'loading.gif' %> Your answers have been submitted, please wait...</h3>
	</div> 
<% end %>
</div>



<div id="loading">
	<h3><%= image_tag 'loading.gif' %> Your answers have been submitted, please wait...</h3>
</div>

<style>
	#loading {
		display: none;
	}
</style>

app/views/rounds/summary.html.erb
<h1>Round Summary</h1>
<p>&nbsp;</p>
<div class="row">
  <div class="span2">
    <h3>Project Name</h3>
  </div>
  
  <div class="span4">
    <h3>Funding Status</h3>
  </div>
  
  <div class="span6">
    &nbsp;
  </div>
</div>
<p>&nbsp;</p>

<% @current_round.projects.each do |p| %>
	<%= render :partial => 'projects/stats', :locals => { :project => p, :admin => false }%>
<% end %>
<p>&nbsp;</p>

<div class="row">
  <div class="span12">
  <h2>Round Details</h2>
  <br>
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th><h3>Project Name</h3></th>
          <th><h3>Payouts</h3></th>
          <th><h3>Funding Status</h3></th>
          <th><h3>Credits</h3></th>
          <%# if current_experiment.return_credits%>
            <!-- <th><h3>Credits Returned</h3></th> -->
          <%# end %>
        </tr>
      </thead>
      <tbody>
        <tr>
        
        <!-- name A -->
    	  <th><%= @current_round.projects.order('id ASC').first.name %></th>
    	  <!-- payout -->
    	  <th><%= @preferences.a_payout %></th>
    	  
    	  <!-- funding status -->
    	  <th>
	    	  <% if @current_round.projects[0].goal_amount <= @current_round.projects[0].funded_amount %>
    	        <font color="#468847">Funded</font>
              <% else %>
    	        <font color="#B94A48">Not Funded</font>
              <% end %>
    	  </th>
    	  
    	  <!-- credits earned -->
    	  <th>
            <% if @current_round.projects[0].funded? %>
              <font color="#468847"><%= @preferences.a_payout %> credits earned</font>
            <% elsif current_experiment.return_credits %>
            	<font color="#B94A48"><%= @contributions.where(:project_id => @current_round.projects[0]).first.amount %> credits returned</font>
            <% else %>
              0
            <% end %>
        </th>
        </tr>
        <tr>
        
        <!-- name B -->
	      <th><%= @current_round.projects.order('id ASC').second.name %></th>
	      <!-- payout -->
	      <th><%= @preferences.b_payout %></th>
	      
	      <!-- funding status -->
	      <th>
	    	  <% if @current_round.projects[1].goal_amount <= @current_round.projects[1].funded_amount %>
    	        <font color="#468847">Funded</font>
          <% else %>
    	        <font color="#B94A48">Not Funded</font>
           <% end %>
    	  </th>
    	  
    	  <!-- credits earned -->
    	  <th>
            <% if @current_round.projects[1].funded? %>
              <font color="#468847"><%= @preferences.b_payout %> credits earned</font>
            <% elsif current_experiment.return_credits %>
            	<font color="#B94A48"><%= @contributions.where(:project_id => @current_round.projects[1]).first.amount %> credits returned</font>
            <% else %>
              0
            <% end %>
        </th>
        </tr>
        <tr>
        
        <!-- name C -->
	      <th><%= @current_round.projects.order('id ASC').third.name %></th>
	      <!-- payout -->
	      <th><%= @preferences.c_payout %></th>
	      
	      <!-- funding status -->
	      <th>
	    	  <% if @current_round.projects[2].goal_amount <= @current_round.projects[2].funded_amount %>
    	        <font color="#468847">Funded</font>
          <% else %>
    	        <font color="#B94A48">Not Funded</font>
          <% end %>
    	  </th>
    	  
    	  <!-- credits earned -->
    	  <th>
            <% if @current_round.projects[2].funded? %>
              <font color="#468847"><%= @preferences.c_payout %> credits earned</font>
            <% elsif current_experiment.return_credits %>
            	<font color="#B94A48"><%= @contributions.where(:project_id => @current_round.projects[2]).first.amount %> credits returned</font>
            <% else %>
              0
            <% end %>
        </th>
        </tr>
        <tr>
        
        <!-- name D -->
	      <th><%= @current_round.projects.order('id ASC').fourth.name %></th>
	      <!-- payout -->
	      <th><%= @preferences.d_payout %></th>
	      <!-- funding status -->
	      <th>
	    	  <% if @current_round.projects[3].goal_amount <= @current_round.projects[3].funded_amount %>
    	        <font color="#468847">Funded</font>
          <% else %>
    	        <font color="#B94A48">Not Funded</font>
          <% end %>
    	  </th>
    	  
    	  <!-- credits earned -->
    	  <th>
            <% if @current_round.projects[3].funded? %>
              <font color="#468847"><%= @preferences.d_payout %> credits earned</font>
            <% elsif current_experiment.return_credits %>
            	<font color="#B94A48"><%= @contributions.where(:project_id => @current_round.projects[3]).first.amount %> credits returned</font>
            <% else %>
              0
            <% end %>
        </th>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
	<div class="span4 offset8">
		<h3>Credits Not Donated: <font color="#F89406"><%= @not_donated %></font></h3>
	</div>
<br>
</div>

<div class="row">
	<div class="span4">
	<h2>Total Round Payout: </h2>
	<h2>Total Credits Banked: </h2>
	</div>
	
	<div class="span8">
	<h2><%= @preferences.round_payout %> <small> =
		<font color="#F89406">
		<%= @not_donated %>
		</font>
		<font color="#468847"> 
		<%= " + #{@preferences.a_payout}" if @current_round.projects[0].funded? %> 
		<%= " + #{@preferences.b_payout}" if @current_round.projects[1].funded? %> 
		<%= " + #{@preferences.c_payout}" if @current_round.projects[2].funded? %> 
		<%= " + #{@preferences.d_payout}" if @current_round.projects[3].funded? %>
		</font>
		<% if current_experiment.return_credits %>
			<font color="#B94A48">
			<%= " + #{@contributions.where(:project_id => @current_round.projects[0]).first.amount}" unless @current_round.projects[0].funded?%>
			<%= " + #{@contributions.where(:project_id => @current_round.projects[1]).first.amount}" unless @current_round.projects[1].funded?%>
			<%= " + #{@contributions.where(:project_id => @current_round.projects[2]).first.amount}" unless @current_round.projects[2].funded?%>
			<%= " + #{@contributions.where(:project_id => @current_round.projects[3]).first.amount}" unless @current_round.projects[3].funded?%>
			</font>
		<% end %>
	</small></h2>
	<h2><%= current_user.payout %></h2>
	</div>
</div>

<p>&nbsp;</p>
<%= link_to "Ready for Next Round", round_waiting_path(@next_round), :class => 'btn-success btn-large' unless last_round?(@current_round) %>
<%= link_to "Experiment Summary", experiment_summary_waiting_path(current_experiment), :class => 'btn-success btn-large' if last_round?(@current_round)%>
<p>&nbsp;</p>

app/views/rounds/waiting_for_round.html.erb
<%= render :partial => 'shared/waiting', :locals => { :message => "Waiting..." } %>
<h3>Stand by for next round. </h3>

<script type="text/javascript">
	window.setTimeout(function() {
    	window.location.reload()
    }, 2000);
</script>

app/views/rounds/waiting_for_summary.html.erb
<%= render :partial => 'shared/waiting', :locals => {:message => "Waiting..." } %>
<h3>Please stand by while other participants finish the round.</h3>

<script type="text/javascript">
    window.setTimeout(function() {
    	window.location.reload()
    }, 2000);
</script>