config/routes.rb
CrowdfundingExperiment::Application.routes.draw do

	match "/instructions" => "users#instructions", :as => :instructions
	match "/instructions_iframe" => "users#instructions_iframe", :as => :instructions_iframe
	
	match "/questions" => "users#questions", :as => :questions
	match "/questions/submit" => "users#submit"
	
	match "/preferences/:id/flag" => "preferences#flag", :as => :flag_user
	match "/preferences/submit-flag" => "preferences#flag_submit"
	match "/preferences/:id/unflag" => "preferences#unflag", :as => :unflag_user
	
	match "/contributions/submit" => "contributions#submit"
	  
  match "/rounds/:id/summary" => "rounds#summary", :as => :round_summary
  match "/rounds/:id/summary/waiting" => "rounds#waiting_for_summary", :as => :summary_waiting
  match "/rounds/:id/waiting" => "rounds#waiting_for_round", :as => :round_waiting
  
  match "/experiments/:id/admin" => "experiments#dashboard", :as => :dashboard
  match "/experiments/:id/users" => "experiments#users", :as => :experiment_users
  match "/experiments/:id/summary" => "experiments#summary", :as => :experiment_summary
  match "/experiments/:id/final-summary/waiting" => "experiments#waiting_for_summary", :as => :experiment_summary_waiting
  match "/experiments/:id/final-summary" => "experiments#final_summary", :as => :final_experiment_summary
  
  resources :users, :only => [:create]
  resources :projects, :only => [:create]
  resources :rounds, :only => [:create, :show]
  resources :experiments, :only => [:new, :create, :index]
  resources :preferences, :only => [:create]
  resource :user_sessions, :only => [:create, :destroy]
  resources :contributions, :only => [:create]

  root :to => "user_sessions#new"
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base

	#has_many :rounds, :dependent => :destroy
	has_many :groups
	has_many :rounds, :through => :groups
	has_many :users, :dependent => :destroy
	# has_one :admin
	
	after_create :generate_groups
	after_create :generate_users
	after_create :set_current_round_and_generate_prefs
	after_create :mgaic_preferences
	
	def generate_users
		NUMBER_OF_USERS_PER_GROUP.times do
			@user1 = User.create(:name => "temp")
			self.users << @user1
			#self.groups.first.users << @user1
			#self.groups.first.save!
			
			@user2 = User.create(:name => "temp")
			self.users << @user2
			#self.groups.last.users << @user2
			#self.groups.last.save!
		end
		self.save!
	end
	
	def generate_groups
		reseed_names
		self.groups << Group.create(:name => 'A')
		reseed_names
		self.groups << Group.create(:name => 'B')
		self.save!
	end
	
	def set_current_round_and_generate_prefs
		self.groups.each do |g|
			g.generate_prefs
		end
		
		self.current_round_number = 1
		self.save!
	end
	
	def start_experiment
		self.started = true
		self.save!
	end
	
	def experiment_over
		self.users.each do |user|
			user.payout = 0
			@preferences = Preferences.where(:user_id => user.id)
			@preferences.each do |pref|
				user.payout += pref.round_payout
			end
			user.save!
		end
	
		self.finsihed_calc = true
		self.save!
	end
	
	def reseed_names
			require 'csv'
			$project_names = []
			CSV.foreach("colors4.csv", :headers => false) do |row|
			  $project_names << row[0]
			end
			
			$project_names.each do |n|
				n.gsub!(";",'')
			end
	end
	
	def mgaic_preferences
		self.users.each_with_index do |u, i|
			NUMBER_OF_ROUNDS.times do |r|
				if i < 6 #first 6 people
				
					# pick a random group
					@rand = rand(0...2)
					@group = nil
					
					case @rand
					when 1
						@group = self.groups[0] #.first
					when 0
						@group = self.groups[1] #.last
					end
					
					# put them in that group with the correct preferences
					@roundPrefs = @group.rounds.where(:number => r + 1).first.prefs					
					@prefs = @roundPrefs.where(:kind_of => ((r + i) % 6) + 1).first
					@prefs.user_id = u.id
					@prefs.save!
					
					u.group_id = @group.id
					u.save!
				else #last 6 people
					
					# Is there already a user in the first group with the preferences I need? If not, put them in that group, if so put them in the other group.
					if self.groups.first.rounds.where(:number => r + 1).first.prefs.where(:kind_of => ((r + i) % 6) + 1).first.user_id.nil?
						@prefs = self.groups.first.rounds.where(:number => r + 1).first.prefs.where(:kind_of => ((r + i) % 6) + 1).first
						@prefs.user_id = u.id
						@prefs.save!
						
						u.group_id = self.groups.first.id
						u.save!
					elsif self.groups.last.rounds.where(:number => r + 1).first.prefs.where(:kind_of => ((r + i) % 6) + 1).first.user_id.nil?
						@prefs = self.groups.last.rounds.where(:number => r + 1).first.prefs.where(:kind_of => ((r + i) % 6) + 1).first
						@prefs.user_id = u.id
						@prefs.save!
						
						u.group_id = self.groups.last.id
						u.save!
					else
						# this will cause the thing to explode and give you an error during db:seed telling you somthing is wrong
						qq = xx
					end

				end
			end
		end
	end
end

app/controllers/experiments_controller.rb
class ExperimentsController < InheritedResources::Base
	def create
		require_admin
		@experiment = Experiment.new(params[:experiment])
		
    if @experiment.save
      redirect_to dashboard_path(@experiment)
    else
    	flash[:error] = "Failed to create a new experiment."
    	redirect_to experiments_path
    end
	end
	
	def users
		@experiment = Experiment.find(params[:id])
	end
	
	def summary
		@user = current_user
		@preferences = @user.preferences
		@preferences.sort! {|a,b| Round.find(a.round_id).number <=> Round.find(b.round_id).number}
	end
	
	def final_summary
		@user = current_user
		@preferences = @user.preferences
		@preferences.sort! {|a,b| Round.find(a.round_id).number <=> Round.find(b.round_id).number}
	end
	
	def waiting_for_summary
		if current_experiment.finsihed_calc
			redirect_to experiment_summary_path(current_experiment)
		end
	end
	
	def dashboard
		require_admin
		@experiment = Experiment.find(params[:id])
		@roundsA = @experiment.groups.first.rounds.where(:number => (1..@experiment.current_round_number)).order("number DESC")
		@roundsB = @experiment.groups.last.rounds.where(:number => (1..@experiment.current_round_number)).order("number DESC")
		
		if @roundsA.first.finished and @roundsB.first.finished
			@roundsA = @experiment.groups.first.rounds.where(:number => (1..@experiment.current_round_number + 1)).order("number DESC")
			@roundsB = @experiment.groups.last.rounds.where(:number => (1..@experiment.current_round_number + 1)).order("number DESC")
		end
		
	end
	
	def new
		require_admin
		@experiment = Experiment.new
	end
	
	def index
		require_admin
		@experiments = Experiment.all
	end
end

app/helpers/experiment_helper.rb
module ExperimentHelper
end

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this session from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :return_credits %>
    <%= f.radio_button :return_credits, true %> Credits are returned to users if proejct is not funded.<br>
    <%= f.radio_button :return_credits, false %> Credits ARE NOT returned to users if project is funded.
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/dashboard.html.erb
  <script type="text/javascript">
    $(document).ready(function(){
      $(".iframe-flag").colorbox({iframe:true, width:"43%", height:"45%"});
    });
  </script>

<% if !@experiment.finished %>
	<meta http-equiv="refresh" content="6" />
<% end %>
<%= link_to 'Back to experiments', experiments_path %>
<div class="page-header">
<h1>Experiment <%= @experiment.id %></h1>
</div>
<br>

<% if @experiment.finsihed_calc %>
<h2>Experiment Summary</h2>
	<table class="table table-striped table-bordered">
	<thead><tr><td>User</td><td>Status</td><td>Payout (credits)</td><td>Payout (dollars)</td></tr></thead>
	<% @experiment.users.each do |u| %>
		<tr>
		<td><%= u.name %></td>
		<td>
		<% if u.question_1A.nil? %>
			<span class="badge badge-warning">Answering Questions</span></td>
		<% else %>
			<span class="badge badge-success">Finsihed</span>
			<td><%= u.payout %></td>
			<td><%= to_dollars(u.payout) %></td>
		<% end %>
		</td>
		</tr>
	<% end %>
	</table>
	<br>
<% end %>

<% (NUMBER_OF_ROUNDS * 2).times do |i| %>
<%# 0.times do %>
<% 2.times do |j|%>

<% if j==0 %>
	<% r = @roundsA[i] %>
<% else %>
	<% r = @roundsB[i] %>
<% end %>
<% if r.nil? %>
	<% break %>
<% end %>
	
	<h2>Round <%= r.number %> <small>Id <%= r.id %> | Group <%= r.group.name %> | 
	<% if r.finished %>
		Round Complete </small></h2>
		<div class="row">
		  <div class="span2">
		    <h3>Project Name</h3>
		  </div>
		  
		  <div class="span4">
		    <h3>Funding Status</h3>
		  </div>
		  
		  <div class="span6">
		    &nbsp;
		  </div>
		</div>
		<p>&nbsp;</p>
		
		<% r.projects.each do |p| %>
			<%= render :partial => 'projects/stats', :locals => { :project => p, :admin => true }%>
		<% end %>
		
		<table class="table table-striped table-bordered table-condensed">
		<thead><tr>
			<td>Flag</td>
			<td>User</td>
			<td>A Payout</td>
			<td>B Payout</td>
			<td>C Payout</td>
			<td>D Payout</td>
			<td>Payout (for this round)</td>
			</tr></thead>
		<% r.users.order('id ASC').each do |u| %>
			<% @pref = Preferences.where(:user_id => u.id, :round_id => r.id).first %>
		 <tr>
		 	<td>
		 		<% if @pref.flag %>
		 			<%= link_to "unflag", unflag_user_path(@pref), :class => "label label-info" %>
		 		<% else %>
		 			<%= link_to "flag", "/preferences/#{@pref.id}/flag?header=false", :onclick => "window.open(this.href,'window','width=580,height=275,resizable,scrollbars,toolbar,menubar') ;return false;" %>
		 			<%#= link_to "flag", flag_user_path(@pref) %>
		 		<% end %>
		 	</td>
		 	<td><%= u.name %></td>
		 	<td><%= @pref.a_payout %></td>
		 	<td><%= @pref.b_payout %></td>
		 	<td><%= @pref.c_payout %></td>
		 	<td><%= @pref.d_payout %></td>
		 	<td><%= @pref.round_payout %></td>
		 </tr>
		<% end %>
		</table>
		
	<% elsif r.started %>
		Round In Progress </small></h2>		
		<% r.users.order("id ASC").each do |u| %>
			<tr>
			<td><%= u.name %></td>
			<td>
			<% if Preferences.where(:user_id => u.id, :round_id => r.id).first.finished_and_ready %>
				<span class="badge badge-success">Finished</span>
			<% else %>
				<span class="badge badge-warning">Still Picking</span>
			<% end %>
			</td>
			</tr>
		<% end %>
		
	<% else %>
		Round Not Started </small></h2>
		
		<% r.users.each do |u| %>
			<tr>
			<td><%= u.name %></td>
			<td>
			<% if Preferences.where(:user_id => u.id, :round_id => r.id).first.ready_to_start %>
				<span class="badge badge-success">Ready</span>
			<% else %>
				<span class="badge badge-warning">Not Ready</span>
			<% end %>
			</td>
			</tr>
		<% end %>
	
	<% end %>
	<br>
<% end %>

<% end %>

app/views/experiments/final_summary.html.erb
<h2>Final Payout: </h2>
<table class="table">
<thead>
	<tr>
	<td>Round Number</td>
	<td>Round Payout</td>
	</tr>
</thead>

<% @preferences.each_with_index do |p,i| %>
	<tr>
		<td><%= i + 1 %><%#= Round.find(p.round_id).number %></td>
		<td><%= p.round_payout  %></td>
	</tr>
<% end %>
<tr>
	<td>Extra Credit</td>
	<td><%= current_user.questions_payout %></td>
</tr>
</table>

<h3>Total: <%= @user.payout unless @user.payout.nil?%><%= "0" if @user.payout.nil? %> credits or <%= to_dollars(@user.payout) %> dollars.</h3>

<p>&nbsp;</p>
<p><%= link_to "Continue to short survey", "https://bitlab.cas.msu.edu/survey/index.php?lang=en&sid=11363&token=#{@user.token}" , :class => 'btn-success btn-large'%></p>

app/views/experiments/index.html.erb
<div class="row">
<div class="span12">
<h1>Listing Experiments</h1>

<table class="table">
	<thead>
  <tr>
    <td>Experiment Id</td>
    <td>Start Time</td>
    <td>Return Credits</td>
    <td>Actions</td>
    <td></td>
    <td></td>
  </tr>
	</thead>

<% @experiments.each do |experiment| %>
  <tr>
  	<td><%= experiment.id %></td>
  	<td><%=l experiment.start_time, :format => :default unless experiment.start_time.nil?%></td>
  	<td><%= experiment.return_credits %></td>
    <td><%= link_to 'Show', dashboard_path(experiment) %></td>
    <td><%= link_to 'Users', experiment_users_path(experiment) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Experiment', new_experiment_path %>
</div>
</div>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/summary.html.erb
<h2>Total Payout: </h2>
<table class="table">
<thead>
	<tr>
	<td>Round Number</td>
	<td>Round Payout</td>
	</tr>
</thead>

<% @user.preferences.order('updated_at ASC').each_with_index do |p,i| %>
	<tr>
		<td><%= Round.find(p.round_id).number %></td>
		<td><%= p.round_payout %></td>
	</tr>
<% end %>
</table>


<h3><%= @user.payout unless @user.payout.nil?%><%= "0" if @user.payout.nil? %> credits or <%= to_dollars(@user.payout) %> dollars.</h3>

<p>&nbsp;</p>
<p><h4>Next, click continue below to ansawer some questions.</h4></p>
<p><%= link_to "Continue", questions_path, :class => 'btn-success btn-large' %></p>

app/views/experiments/users.html.erb
<%= link_to 'Back to experiments', experiments_path %>
<table class="table table-striped table-bordered">
<thead>
<tr><td><h4>User</h4></td><td><h4>Password</h4></td></tr>
</thead>
<tbody>
<% @experiment.users.each do |u| %>
	<tr>
	<td><%= u.name %></td>
	<td><%= u.password %></td>
	</tr>
<% end %>
</tbody>
</table>

app/views/experiments/waiting_for_summary.html.erb
<%= render 'shared/waiting' %>
<h3>Please stand by.</h3>