config/routes.rb
CrowdfundingExperiment::Application.routes.draw do

	match "/instructions" => "users#instructions", :as => :instructions
	match "/instructions_iframe" => "users#instructions_iframe", :as => :instructions_iframe
	
	match "/questions" => "users#questions", :as => :questions
	match "/questions/submit" => "users#submit"
	
	match "/preferences/:id/flag" => "preferences#flag", :as => :flag_user
	match "/preferences/submit-flag" => "preferences#flag_submit"
	match "/preferences/:id/unflag" => "preferences#unflag", :as => :unflag_user
	
	match "/contributions/submit" => "contributions#submit"
	  
  match "/rounds/:id/summary" => "rounds#summary", :as => :round_summary
  match "/rounds/:id/summary/waiting" => "rounds#waiting_for_summary", :as => :summary_waiting
  match "/rounds/:id/waiting" => "rounds#waiting_for_round", :as => :round_waiting
  
  match "/experiments/:id/admin" => "experiments#dashboard", :as => :dashboard
  match "/experiments/:id/users" => "experiments#users", :as => :experiment_users
  match "/experiments/:id/summary" => "experiments#summary", :as => :experiment_summary
  match "/experiments/:id/final-summary/waiting" => "experiments#waiting_for_summary", :as => :experiment_summary_waiting
  match "/experiments/:id/final-summary" => "experiments#final_summary", :as => :final_experiment_summary
  
  resources :users, :only => [:create]
  resources :projects, :only => [:create]
  resources :rounds, :only => [:create, :show]
  resources :experiments, :only => [:new, :create, :index]
  resources :preferences, :only => [:create]
  resource :user_sessions, :only => [:create, :destroy]
  resources :contributions, :only => [:create]

  root :to => "user_sessions#new"
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < InheritedResources::Base

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
    	if current_user.name == 'admin'
    		return redirect_to experiments_path
    	else
      	redirect_to instructions_path
      end
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy unless current_user_session.nil?
    redirect_to root_path
  end
end

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="span1">
    <%= f.label :name %>
  </div>
  <div class="span3">  
    <%= f.text_field :name %>
  </div>
</div>

<div class="row">
  <div class="span1">
    <%= f.label :password %>
  </div>
  <div class="span3">  
    <%= f.password_field :password %>
  </div>
</div>  

<div class="row">
  <div class="span1 offset1">
    <%= f.submit "Login", :class => 'btn-success' %>
  </div>
</div>  

<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<br>
<br>
<%= render 'form' %>
<br>
<br>
<%= link_to "LOG OUT", user_sessions_path, :method => :delete unless current_user.nil? %>